Homework6.4
ArtemRadchuk/homework pull request #29
Opened 2022-03-28 07:08 UTC by ArtemRadchuk

2022-04-06 06:02 UTC, CALLIKA312 requested changes

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +    HashMap<String, String> PhoneBook = new HashMap<>();
12 Все поля классов должны быть приватными и быть доступными только через методы
(геттеры и сеттеры).
5. Имена переменных, полей классов, параметров методов и самих методов пишутся с
маленькой буквы в lowerCamelCase.
Правильней хранить Ключ, Зачение, как Телефон, Имя, т.к. имена могут повторяться, а телефоны являются уникальными идентификаторами.

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +    public boolean unCorrectPhone(String phone) {
unCorrectPhone и unCorrectName являются внутренними методами класса и не должны вызываться в других классах

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +    public boolean unCorrectPhone(String phone) {
Правильнее будет назвать методы phoneValidate и nameValidate

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +            System.out.println("Некорректный формат имени");
Здесь проверяется на корректонсть не только имя, но и телефон

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +        if (unCorrectName(name) == false && unCorrectPhone(phone) == false) {
Метод возвращает true, если строка пройдет валидацию. 
matcher.find() 
Returns:
true if, and only if, a subsequence of the input sequence matches this matcher's pattern

Здесь не нужно сравнивать с true или false. Булевые значения уже вляются условиями для if.

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +               String addPhone = PhoneBook.get(name) + ", " + phone;
16. Код должен быть отформатирован так же, как это бы произошло при нажатии сочетания
клавиш Alt + Ctrl + L в IDEA (пробелы после запятых, по краям от арифметических знаков и
т.д).

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +            }else if (phone != "" && name != "") {
Корректнее проверять пустоту строк как String.isEmpty()

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +    public String getKey(String phone) {
В этом методе проблема с неймингов, не понятно что такое key, какие данные в себе хранит collection.

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +            if (key != null) {
2 условия можно объединить в 1

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +    public String getContactByPhone(String phone) {
Как в предыдущем проблема с неймингом и это 2 одинаковых метода

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +    public Set<String> getContactByName(String name) {
Зачем здесь возвращается Set, если всегда в нём не более 1 строки

2022-04-06 06:02 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/Main.java
> +        PhoneBook a = new PhoneBook();
Задача подразумевает обработку сообщений пользователя через интерфейс консоли

2022-04-06 08:11 UTC, ArtemRadchuk commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +    public Set<String> getContactByName(String name) {
Я не знаю, изначально в задании был описан метод именно так

2022-04-08 13:38 UTC, CALLIKA312 requested changes

2022-04-08 13:38 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/Main.java
> +            Pattern pattern = Pattern.compile("[0-9]");
Нужно выносить инициализацию за цикл, если переменная не должна обновляться.

2022-04-08 13:38 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/Main.java
> +            if (matcher.find() && input.equals("LIST") == false) {
Не нужно это проверять если выше было вхождение по этому же условию.
P.S. Можно просто писать !String.equals(String str), т.к. String.equals() возвращает boolean значение.

2022-04-08 13:38 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +    private HashMap<String, String> phoneBook = new HashMap<>();
Правильней хранить Ключ, Зачение, как Телефон, Имя, т.к. имена могут повторяться, а телефоны являются уникальными идентификаторами.

2022-04-08 13:38 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +            } else if (phone != "" && name != "") {
Корректнее проверять пустоту строк как String.isEmpty()

2022-04-08 13:38 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +        Collection<String> collection = phoneBook.keySet();
В этом методе проблема с неймингов, не понятно что такое key, какие данные в себе хранит collection.
 Collection<String> nameCollection или просто names
 for (String name : names) 
 Так намного понятнее по чему идёт обход

2022-04-08 13:38 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +            if (key != null && phone.equals(find)) {
Откуда в коллекции может взяться null?

2022-04-08 13:38 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +    public String getContactByPhone(String phone) {
Нейминг

2022-04-08 13:38 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +    public Set<String> getContactByName(String name) {
Если вводим существующее имя или номер телефона, программа выводит телефон(ы) или имя абонента соответственно.
Если речь идет об этом, то нужно и собирать ВСЕ телефоны, а не первое вхождение по имени.

2022-04-08 13:38 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/PhoneBook.java
> +            String key = entry.getKey();
Опять нейминг, key это имя или телефон, то же с value.

2022-04-08 13:39 UTC, CALLIKA312 commented on Array/PhoneBook/src/main/java/practice/Main.java
> +            } else if (matcher.find() == false && input.equals("LIST") == false) {
Выше исправил что matcher.find() без сравнения, а здесь оставил.

2022-05-05 09:34 UTC, merged