Homework6.5
ArtemRadchuk/homework pull request #30
Opened 2022-03-29 08:45 UTC by ArtemRadchuk

2022-04-06 06:21 UTC, CALLIKA312 requested changes

2022-04-06 06:21 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/Main.java
> +    public static void main(String[] args) {
Нет реализации поиска номеров в мейне.
3. Измерьте и выведите длительность каждого метода поиска.

Формат вывода результатов поиска:

Поиск перебором: номер найден/не найден, поиск занял 34нс
Бинарный поиск: номер найден/не найден, поиск занял 34нс
Поиск в HashSet: номер найден/не найден, поиск занял 34нс
Поиск в TreeSet: номер найден/не найден, поиск занял 34нс

2022-04-06 06:21 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +    public static ArrayList<String> CoolNumber = new ArrayList<>();
Это должна быть приватная переменная. В задании не было указано про статичность переменных и методов. Это лишнее.
Название переменной с маленькой буквы.

2022-04-06 06:21 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +        int N = 0;
Это относится ко всем следующим переменным.
13. Если значение поля не меняется в процессе выполнения, оно должно быть final.
Если планируется изменять эти значения то есть смысл их инициализировать. Иначе лучше делать это в цикле, т.к. он сам их создает и отчищает после цикла обработки.

2022-04-06 06:21 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +        for (R = 1; R <= RMax; R++) {
Лишнее присваивание уже инициализированных переменных.

2022-04-06 06:21 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +                            if (R < 10) {
Такого условия в задании нет XNNNYZR — пример: A111BC197, У777HC66.

2022-04-06 06:21 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +        String[] array = CoolNumber.toArray(new String[0]);
В задании явно сказать что обход должен быть по ArrayList
for (String s: CoolNumber){
        }

2022-04-06 06:21 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +        if (out == true) {
Проверка булевого значения не требует сравнения. if (out)

2022-04-06 06:21 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +        boolean out = false;
Правильнее назвать переменную по её значению. isFind

2022-04-06 06:21 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +                out = true;
Нужно сделать выход из цикла break или return прямо здесь, иначе время поиска для любого номера будет одинаковое.

2022-04-06 06:21 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +    public static boolean binarySearchInList(List<String> sortedList, String number) {
Ошибики аналогичные предыдущему методу

2022-04-06 07:00 UTC, Filinnick requested changes

2022-04-06 07:00 UTC, Filinnick commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +        String a = "АВЕКМНОРСТУХ";
7 Названия должны нести смысловую нагрузку и желательно не сокращаться (кроме
   общепринятых сокращений типа Impl, Config, App).

13 Если значение поля не меняется в процессе выполнения, оно должно быть final. 
14 Константы должны быть static final. Без static это не константы.
Следовательно

6 Имена констант пишутся большими буквами в SCREAMING_SNAKE_CASE.

*Касается переменной "a".

2022-04-08 13:49 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +        for (R = 1; R <= RMax; R++) {
Не исправил ошибки инциализации. Нет смысла инициализировать переменные до цикла, если они используются только в нём, тем более если снова делаешь их присваивание в блоке цикла.

2022-04-08 14:00 UTC, CALLIKA312 requested changes

2022-04-08 14:00 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +        if (isFind == true) {
Опять справниваешь boolean значение с true/false.

2022-04-08 14:00 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +    public static boolean binarySearchInList(List<String> sortedList, String number) {
Метод называется InList делаешь поиск по массиву.

2022-04-08 14:00 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +        boolean out = false;
Нейминг

2022-04-08 14:00 UTC, CALLIKA312 commented on Array/CoolNumbers/src/main/java/practice/CoolNumbers.java
> +                isFind = true;
Reply: Нужно сделать выход из цикла break или return прямо здесь, иначе время поиска для любого номера будет одинаковое.

2022-05-05 09:38 UTC, merged