Homework10.1
ArtemRadchuk/homework pull request #35
Opened 2022-04-08 06:59 UTC by ArtemRadchuk

2022-04-15 09:50 UTC, Filinnick requested changes

2022-04-15 09:50 UTC, Filinnick commented on ExceptionsDebuggingAndTesting/ConsoleCustomerList/src/main/java/CustomerStorage.java
> +        if (emailValidate(components[INDEX_EMAIL]) && phoneValidate(components[INDEX_PHONE]) == false && components.length == 4) {
Мне кажется, более корректным и наглядным будет вынести блок проверок в отдельный метод, например, inputValidate. И в нем уже вызывать этот ряд проверок.

2022-04-15 09:50 UTC, Filinnick commented on ExceptionsDebuggingAndTesting/ConsoleCustomerList/src/main/java/CustomerStorage.java
> +        final int INDEX_NAME = 0;
Не реализована "защита" от преждевременного завершения работы метода.

2022-04-15 09:50 UTC, Filinnick commented on ExceptionsDebuggingAndTesting/ConsoleCustomerList/src/main/java/CustomerStorage.java
> +        Pattern phonePattern = Pattern.compile("[A-Z]", Pattern.CASE_INSENSITIVE);
В номере "лишними" могут быть не только буквы, а и различные символы вроде "*", "!" и т.д.

2022-04-18 07:08 UTC, ArtemRadchuk commented on ExceptionsDebuggingAndTesting/ConsoleCustomerList/src/main/java/CustomerStorage.java
> +        if (emailValidate(components[INDEX_EMAIL]) && phoneValidate(components[INDEX_PHONE]) == false && components.length == 4) {
inputValidate должен выдавать true или false, и если false Ошибка будет неверный майл или телефон?
Мне все в одно сделать выходит?

2022-04-18 07:44 UTC, ArtemRadchuk commented on ExceptionsDebuggingAndTesting/ConsoleCustomerList/src/main/java/CustomerStorage.java
> +        final int INDEX_NAME = 0;
Не до конца понимаю про защиту 
Что там должно быть

2022-04-18 07:46 UTC, ArtemRadchuk commented on ExceptionsDebuggingAndTesting/ConsoleCustomerList/src/main/java/CustomerStorage.java
> +        if (emailValidate(components[INDEX_EMAIL]) && phoneValidate(components[INDEX_PHONE]) == false && components.length == 4) {
Я про то что не будет отдельных ошибок под номер и мейл

2022-05-05 09:45 UTC, merged