Homework10.2
ArtemRadchuk/homework pull request #37
Opened 2022-04-12 10:22 UTC by ArtemRadchuk

2022-04-19 16:49 UTC, CALLIKA312 requested changes

2022-04-19 16:49 UTC, CALLIKA312 commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/core/Station.java
> +public class Station implements Comparable<Station>
Не забывай использовать Ctrl+Alt+L

2022-04-19 16:49 UTC, CALLIKA312 commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/StationIndex.java
> +            if (!connections.containsKey(station)) {
Тут лучше сделать сразу инициализацию с сохранением.
if (!connections.containsKey(station)) {
        TreeSet<Station> connectedStations =  new TreeSet<>();
        connectedStations.addAll(stations.stream()
                    .filter(s -> !s.equals(station)).collect(Collectors.toList()));
        connections.put(station,connectedStations);
}

2022-04-19 16:49 UTC, CALLIKA312 commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/StationIndex.java
> +    private final Map<Integer, Line> number2line;
Нейминг. Я не понял для чего эта переменная. Если хранить мапу Линий, то можно просто Map<Line> хранить и у них вызывать getNumber()

2022-04-19 16:49 UTC, CALLIKA312 commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/StationIndex.java
> +        for (Station station : stations) {
Попробуй сделать это через stream(). Будет в 1 строчку, выглядеть лучше.

2022-04-19 16:49 UTC, CALLIKA312 commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/RouteCalculator.java
> +            return null;
тут следует вызывать getRouteOnTheLine(Station from, Station to), т.к. он сделает обход быстрее. Ведь путь с 1 пересадкой существует, просто на этой же линии любая станция может считаться "пересадочной".

2022-04-19 16:49 UTC, CALLIKA312 commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/RouteCalculator.java
> +                        return route;
return route; должен быть после всех обходов, т.к. ты выбрасываешь сейчас первое нахождение пути, а не кратчайшее

2022-04-19 16:49 UTC, CALLIKA312 commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/RouteCalculator.java
> +                connectedRoute = getRouteOnTheLine(srcStation, dstStation);
Idea подсвечивает что эта переменная вообще не используется, не понял в чём её идея была

2022-04-19 16:49 UTC, CALLIKA312 commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/RouteCalculator.java
> +                if (connectedLineRoute == null) {
Проще инверитровать if и записать дальнейший код в этот блок, чем использовать continue

2022-04-19 16:49 UTC, CALLIKA312 commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/Main.java
> +    private static RouteCalculator getRouteCalculator() {
Старайся писать единообразные методы рядом.  getRouteCalculator() createStationIndex()

2022-04-19 16:49 UTC, CALLIKA312 commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/Main.java
> +        for (; ; ) {
Бесконечный цикл, без точки выхода

2022-04-19 16:49 UTC, CALLIKA312 commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/Main.java
> +            String line = scanner.nextLine().trim();
Не используй подобный нейминг, когда у тебя есть понятие Line как класса или объекта. По сути это inputLine или введенная строка пользователем. 
Можено написать userStationName или что-то подобное.

2022-04-20 06:07 UTC, ArtemRadchuk commented on ExceptionsDebuggingAndTesting/SPBMetro/src/main/java/StationIndex.java
> +        for (Station station : stations) {
Тут весь код кроме теста из задания

2022-05-05 09:49 UTC, merged