Homework11.1
ArtemRadchuk/homework pull request #38
Opened 2022-04-15 12:31 UTC by ArtemRadchuk

2022-04-19 17:00 UTC, CALLIKA312 requested changes

2022-04-19 17:00 UTC, CALLIKA312 commented on FilesAndNetwork/src/main/java/Main.java
> +            System.out.println("");
программа должна перехватывать все исключения, возникающие при ошибках чтения файлов и папок, и выводить сообщение об ошибке с трассировкой стека (stack trace).

2022-04-19 17:00 UTC, CALLIKA312 commented on FilesAndNetwork/src/main/java/Main.java
> +        long fileWeight = FileUtils.calculateFolderSize(input);
Зачем передавать путь, если мы уже получили доступ к файлу.
Эту строку лучше вызывать внутри блока try|catch

2022-04-19 17:00 UTC, CALLIKA312 commented on FilesAndNetwork/src/main/java/FileUtils.java
> +        for (File file : folder.listFiles()) {
Прежде требуется проверить, что открытый файл сам является директорией.

2022-04-19 17:00 UTC, CALLIKA312 commented on FilesAndNetwork/src/main/java/FileUtils.java
> +            for (String s : dir) {
Цикл можно внести в блок else if выше.

2022-04-19 17:00 UTC, CALLIKA312 commented on FilesAndNetwork/src/main/java/FileUtils.java
> +            } else if (file.isDirectory()) {
В данному случае проверка else if (file.isDirectory()) и просто else {} являются одним и тем же. Условие 100% выполнится , т.к. является обратным к if()

2022-04-19 17:00 UTC, CALLIKA312 commented on FilesAndNetwork/src/main/java/FileUtils.java
> +                    } else if (f.isDirectory()) {
В данному случае проверка else if (file.isDirectory()) и просто else {} являются одним и тем же. Условие 100% выполнится , т.к. является обратным к if()

2022-04-19 17:00 UTC, CALLIKA312 commented on FilesAndNetwork/src/main/java/FileUtils.java
> +        if (bite == 0) {
Когда много условий в блоке if, лучше использовать switch

2022-05-05 10:07 UTC, irakli8888 commented
смотри в сторону рекурсивного алгоритма, код переработать

2022-05-19 07:34 UTC, merged