Homework12.3
ArtemRadchuk/homework pull request #45
Opened 2022-04-28 09:07 UTC by ArtemRadchuk

2022-05-05 10:52 UTC, irakli8888 commented
https://prog-help.ru/java/sozdanie-i-svjazka-sushhnostej-v-hibernate/

2022-05-05 10:52 UTC, irakli8888 commented
посмотреть видео по hibernate

2022-05-27 04:55 UTC, Filinnick requested changes

2022-05-27 04:55 UTC, Filinnick commented on DataBase12.3/src/main/java/service/StudentPrinterImpl.java
> +
Комментарий правильный, но далее по коду это не сделано. Взаимодействие с бд, т.е. обращения к ней (запросы) лучше выделить в отдельный DAO класс, т.к. результат обращения может быть использован не только в одном-двух методах. Это позволит не писать каждый раз запросы к БД по необходимости, а запросить их один раз, условно, и работать с результатом столько, сколько нужно.

2022-05-27 04:55 UTC, Filinnick commented on DataBase12.3/src/main/java/service/StudentPrinterImpl.java
> +        result = state.executeQuery("select * from courses where id = " + course_id);
Для чего создавал класс Courses?

2022-05-27 11:14 UTC, Filinnick approved these changes

2022-05-27 11:15 UTC, merged